/*
Hopefully this works
This file will contain multiple arrays of objects that will be massive (thts the vision)
For the purposes of code readbilillity and organization

*/

window.lblDailyEcoTasksTitle = [
  { id: "lights", text: "Turn off unused lights", type: "home", reduction: 0.05 },
  { id: "thermostat", text: "Adjust thermostat by 2° (lower in winter/higher in summer)", type: "home", reduction: 0.18 },
  { id: "vampire", text: "Unplug idle electronics", type: "home", reduction: 0.03 },
  { id: "laundryCold", text: "Wash a load of laundry in cold water", type: "home", reduction: 0.25 },
  { id: "airDry", text: "Air-dry clothes instead of using the dryer", type: "home", reduction: 0.45 },
  { id: "shortShower", text: "Take a shower under 5 minutes", type: "home", reduction: 0.15 },
  { id: "dishwasherFull", text: "Run the dishwasher only when completely full", type: "home", reduction: 0.08 },
  { id: "ovenOff", text: "Turn off the oven a few minutes early to use residual heat", type: "home", reduction: 0.02 },
  { id: "insulation", text: "Close curtains/blinds to regulate room temperature", type: "home", reduction: 0.07 },
  { id: "reusableBag", text: "Use a reusable shopping bag", type: "habits", reduction: 0.02 },
  { id: "waterBottle", text: "Use a reusable water bottle (avoid single-use plastic)", type: "habits", reduction: 0.01 },
  { id: "coffeeCup", text: "Use a reusable coffee cup for a drink", type: "habits", reduction: 0.01 },
  { id: "recycle", text: "Properly sort and recycle all eligible materials", type: "habits", reduction: 0.09 },
  { id: "compost", text: "Compost food scraps and yard waste", type: "habits", reduction: 0.12 },
  { id: "thrift", text: "Buy a pre-owned item instead of new", type: "habits", reduction: 0.35 },
  { id: "foodWaste", text: "Eat leftovers/finish all food to avoid waste", type: "habits", reduction: 0.07 },
  { id: "repair", text: "Repair a broken item instead of replacing it", type: "habits", reduction: 0.40 },
  { id: "transit", text: "Take public transit instead of driving", type: "travel", reduction: 0.40 },
  { id: "carpool", text: "Carpool with one or more people", type: "travel", reduction: 0.22 },
  { id: "driveSmart", text: "Avoid hard braking and rapid acceleration", type: "travel", reduction: 0.04 },
  { id: "combineErrands", text: "Combine multiple errands into a single trip", type: "travel", reduction: 0.10 },
  { id: "meatless", text: "Have a completely meatless meal today", type: "habits", reduction: 0.50 },
  { id: "plantMilk", text: "Choose plant-based milk over dairy", type: "habits", reduction: 0.15 },
  { id: "waterOnly", text: "Drink only water (no sugary drinks)", type: "habits", reduction: 0.03 },
  { id: "veggieDay", text: "Go entirely vegetarian for the whole day", type: "habits", reduction: 1.00 },
];

window.tips = [
  "Take a quicker shower! Aim for under 5 minutes.",
  "Unplug electronics when they aren't in use—they still suck 'vampire power.'",
  "Close blinds and curtains during the day in summer to keep cool air in.",
  "Turn down your water heater temperature a few degrees; you won't notice the difference, but the planet will.",
  "Wash your clothes using the cold-water setting whenever possible.",
  "Use a power strip for your desk setup and flip the switch off at night.",
  "Replace old incandescent bulbs with energy-efficient LEDs.",
  "Clean or replace your furnace and air conditioner filters regularly to maintain efficiency.",
  "Switch to paperless billing and electronic receipts to save trees.",
  "Only run your washing machine or dishwasher when you have a full load.",
  "Maximize natural light and use electric lights less during the day.",
  "Check for and seal any drafts around windows and doors.",
  "Use residual heat: turn off your oven a few minutes before food is done.",
  "Stop drinking so much bottled water! Use a reusable bottle.",
  "Keep a pitcher of water in the fridge so you don't run the tap until it gets cold.",
  "Compost fruit and vegetable scraps instead of throwing them away.",
  "Use reusable containers instead of plastic wrap or foil for leftovers.",
  "Buy in bulk when you can to reduce packaging waste.",
  "Say 'no' to straws or carry a reusable metal one.",
  "Always carry your reusable shopping bags for groceries and other errands.",
  "Check the plastic recycling codes; not all plastics are recyclable in your area.",
  "Mend clothes with small tears instead of tossing them.",
  "Donate old clothes and books instead of sending them to the landfill.",
  "Wipe off dirty dishes before rinsing to save water.",
  "Use old t-shirts as rags instead of buying paper towels.",
  "Leave the car at home and walk or bike for trips under two miles.",
  "Plan your errands to combine multiple stops into one efficient trip.",
  "If you must drive, maintain a steady speed and avoid hard braking.",
  "Check your tyre pressure once a month; proper inflation saves gas.",
  "Take advantage of public transportation or carpool when heading to work or school.",
  "Did you know sitting in traffic burns a ton of gas? Check for less congested routes.",
  "If you're waiting for more than 30 seconds, turn your engine off.",
  "If you're considering a new car, look into hybrid or electric options.",
  "Challenge yourself to go meatless for one full day a week.",
  "Eat ugly produce! Perfectly good food often gets tossed for aesthetic reasons.",
  "Buy local and seasonal produce to reduce transportation emissions.",
  "Try a dairy alternative like oat or almond milk; it uses less water and land.",
  "Freeze extra food before it goes bad to prevent food waste.",
  "Grow your own herbs or small vegetables on a windowsill or balcony.",
  "Bring your own container for restaurant leftovers instead of using their Styrofoam.",
  "Focus on plants: a colourful plate is usually a sustainable plate.",
  "Before buying, ask yourself: 'Do I really need this?'",
  "Borrow tools or items you only need once from a neighbour or library.",
  "Fix that leaky toilet or dripping faucet! It wastes gallons of water daily.",
  "When you receive a package, reuse the box and packing materials.",
  "Support companies that prioritize sustainable sourcing and production.",
  "Use both sides of every piece of paper before recycling it.",
  "Volunteer for a local clean-up or tree-planting event.",
  "Learn how to properly recycle unusual items, like batteries and old electronics.",
  "Share this habit with a friend or family member to multiply your impact!",
];
